/* Auto-generated by scripts/generate-store-theme-data.mjs — do not edit.
 * Static slug-keyed map of every store that ships theme overrides.
 * Empty for standalone scaffolds (no stores/ dir) — the resolver
 * then always serves the theme defaults (single-tenant behavior).
 * Regenerated on every dev/build from stores/<slug>/theme/. */
import type {StoreThemeOverrides} from '../store-theme-data';

export const STORE_THEME_OVERRIDES: Record<string, StoreThemeOverrides> = {};
