/* Auto-generated by scripts/generate-store-registry.mjs — do not edit.
 * Regenerated on every dev/build from stores/<slug>/store.json.
 * Empty when the repo has no stores/ registry (standalone scaffolds):
 * the middleware then never rewrites and the app stays single-tenant. */

export interface StoreRegistryEntry {
  slug: string;
  name: string;
  /** Public hostname (from store.json siteUrl) matched against Host. */
  host: string;
  storeDomain: string;
  /** Public Storefront API token — public by design. */
  storefrontToken: string;
}

export const STORE_REGISTRY: StoreRegistryEntry[] = [];

/** Legacy hostname → canonical site URL (store.json redirectHosts).
 * The middleware 308-redirects these before store matching. */
export const REDIRECT_HOSTS: Record<string, string> = {};
