/* Auto-generated by scripts/sync.mjs — do not edit; run `pnpm sync`. */
import type {ThemeSchema} from '@zalify/storefront-kit/react';

export const themeSchema: ThemeSchema = {
  "templates": {
    "404": {
      "sections": {
        "main": {
          "type": "404",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "article": {
      "sections": {
        "main": {
          "type": "article",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "blog": {
      "sections": {
        "main": {
          "type": "blog",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "cart": {
      "sections": {
        "main": {
          "type": "cart",
          "settings": {
            "voucher_code": "WELCOME20",
            "voucher_text": "Get 20% off your first order"
          }
        }
      },
      "order": [
        "main"
      ]
    },
    "collection": {
      "sections": {
        "main": {
          "type": "collection",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "index": {
      "sections": {
        "hero": {
          "type": "hero",
          "blocks": {
            "slide": {
              "type": "_slide",
              "settings": {},
              "blocks": {
                "box": {
                  "type": "_box",
                  "settings": {
                    "position_x": "start",
                    "position_y": "center",
                    "backdrop": true
                  },
                  "blocks": {
                    "eyebrow": {
                      "type": "text",
                      "settings": {
                        "text": "New arrivals",
                        "text_style": "text--eyebrow"
                      }
                    },
                    "heading": {
                      "type": "text",
                      "settings": {
                        "text": "Made for the season ahead.",
                        "text_style": "text--display"
                      }
                    },
                    "text": {
                      "type": "text",
                      "settings": {
                        "text": "Fresh drops and familiar favorites — browse what's new and find your next go-to.",
                        "text_style": "text--normal"
                      }
                    },
                    "button": {
                      "type": "button",
                      "settings": {
                        "label": "Shop new in",
                        "link": "/collections/all"
                      }
                    }
                  },
                  "block_order": [
                    "eyebrow",
                    "heading",
                    "text",
                    "button"
                  ]
                }
              },
              "block_order": [
                "box"
              ]
            }
          },
          "block_order": [
            "slide"
          ],
          "settings": {
            "height": "lg"
          }
        },
        "stories": {
          "type": "stories",
          "blocks": {
            "story-1": {
              "type": "story",
              "settings": {
                "label": "Shop all",
                "link": "/collections/all"
              }
            },
            "story-2": {
              "type": "story",
              "settings": {
                "label": "Best sellers",
                "link": "/collections/best-sellers"
              }
            },
            "story-3": {
              "type": "story",
              "settings": {
                "label": "New in",
                "link": "/collections/all"
              }
            },
            "story-4": {
              "type": "story",
              "settings": {
                "label": "Sale",
                "link": "/collections/sale"
              }
            }
          },
          "block_order": [
            "story-1",
            "story-2",
            "story-3",
            "story-4"
          ],
          "settings": {}
        },
        "featured_collection": {
          "type": "featured-collection",
          "settings": {
            "heading": "Best sellers",
            "collection": "best-sellers",
            "products_to_show": 8
          }
        },
        "editorial": {
          "type": "image-with-text",
          "settings": {
            "image_position": "left",
            "color_scheme": "scheme-3"
          },
          "blocks": {
            "eyebrow": {
              "type": "text",
              "settings": {
                "text": "Our story",
                "text_style": "text--eyebrow"
              }
            },
            "heading": {
              "type": "text",
              "settings": {
                "text": "Made with intention.",
                "text_style": "text--title"
              }
            },
            "text": {
              "type": "text",
              "settings": {
                "text": "Every piece in our catalog earns its place — considered materials, honest prices, and details you'll notice long after the box is gone.",
                "text_style": "text--normal"
              }
            },
            "button": {
              "type": "button",
              "settings": {
                "label": "Shop the collection",
                "link": "/collections/all",
                "style": "button--secondary"
              }
            }
          },
          "block_order": [
            "eyebrow",
            "heading",
            "text",
            "button"
          ]
        },
        "value_props": {
          "type": "multicolumn",
          "settings": {
            "columns": 3,
            "color_scheme": "scheme-2",
            "section_spacing": "lg"
          },
          "blocks": {
            "col-1": {
              "type": "group",
              "settings": {
                "layout_direction": "group--vertical"
              },
              "blocks": {
                "title": {
                  "type": "text",
                  "settings": {
                    "text": "Free shipping",
                    "text_style": "text--title"
                  }
                },
                "text": {
                  "type": "text",
                  "settings": {
                    "text": "On every order over $50 — no codes, no surprises at checkout.",
                    "text_style": "text--normal"
                  }
                }
              },
              "block_order": [
                "title",
                "text"
              ]
            },
            "col-2": {
              "type": "group",
              "settings": {
                "layout_direction": "group--vertical"
              },
              "blocks": {
                "title": {
                  "type": "text",
                  "settings": {
                    "text": "Easy returns",
                    "text_style": "text--title"
                  }
                },
                "text": {
                  "type": "text",
                  "settings": {
                    "text": "30 days to change your mind, with free returns on every order.",
                    "text_style": "text--normal"
                  }
                }
              },
              "block_order": [
                "title",
                "text"
              ]
            },
            "col-3": {
              "type": "group",
              "settings": {
                "layout_direction": "group--vertical"
              },
              "blocks": {
                "title": {
                  "type": "text",
                  "settings": {
                    "text": "Secure checkout",
                    "text_style": "text--title"
                  }
                },
                "text": {
                  "type": "text",
                  "settings": {
                    "text": "Every major payment method, protected end to end.",
                    "text_style": "text--normal"
                  }
                }
              },
              "block_order": [
                "title",
                "text"
              ]
            }
          },
          "block_order": [
            "col-1",
            "col-2",
            "col-3"
          ]
        },
        "closing": {
          "type": "rich-text",
          "settings": {
            "alignment": "center",
            "section_spacing": "lg"
          },
          "blocks": {
            "eyebrow": {
              "type": "text",
              "settings": {
                "text": "Why us",
                "text_style": "text--eyebrow",
                "alignment": "center"
              }
            },
            "heading": {
              "type": "text",
              "settings": {
                "text": "Considered, crafted, delivered.",
                "text_style": "text--title",
                "alignment": "center"
              }
            },
            "button": {
              "type": "button",
              "settings": {
                "label": "Browse everything",
                "link": "/collections/all"
              }
            }
          },
          "block_order": [
            "eyebrow",
            "heading",
            "button"
          ]
        }
      },
      "order": [
        "hero",
        "stories",
        "featured_collection",
        "editorial",
        "value_props",
        "closing"
      ]
    },
    "list-collections": {
      "sections": {
        "main": {
          "type": "collections",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "page.contact": {
      "sections": {
        "main": {
          "type": "page",
          "settings": {}
        },
        "contact_form": {
          "type": "contact-form",
          "settings": {}
        }
      },
      "order": [
        "main",
        "contact_form"
      ]
    },
    "page": {
      "sections": {
        "main": {
          "type": "page",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "password": {
      "layout": "password",
      "sections": {
        "main": {
          "type": "password",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "product": {
      "sections": {
        "main": {
          "type": "product",
          "blocks": {
            "title": {
              "type": "_title",
              "settings": {}
            },
            "variant-picker": {
              "type": "_variant-picker",
              "settings": {}
            },
            "quantity": {
              "type": "_quantity",
              "settings": {}
            },
            "buy-buttons": {
              "type": "_buy-buttons",
              "settings": {}
            },
            "details": {
              "type": "accordion",
              "settings": {
                "heading": "Details",
                "content": "<p>Considered materials, an honest make, and details that hold up to daily use. Care is simple: follow the label, and it will stay with you for years.</p>"
              }
            },
            "description": {
              "type": "_description",
              "settings": {}
            },
            "shipping": {
              "type": "accordion",
              "settings": {
                "heading": "Shipping & returns",
                "content": "<p>Free shipping on orders over $50, with tracking on every parcel. Not quite right? You have 30 days to send it back — free returns, no questions asked.</p>"
              }
            }
          },
          "block_order": [
            "title",
            "variant-picker",
            "quantity",
            "buy-buttons",
            "details",
            "shipping",
            "description"
          ],
          "settings": {}
        },
        "recommendations": {
          "type": "product-recommendations",
          "settings": {}
        }
      },
      "order": [
        "main",
        "recommendations"
      ]
    },
    "search": {
      "sections": {
        "main": {
          "type": "search",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    }
  },
  "customerTemplates": {
    "account": {
      "sections": {
        "main": {
          "type": "main-account",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "activate_account": {
      "sections": {
        "main": {
          "type": "main-activate-account",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "addresses": {
      "sections": {
        "main": {
          "type": "main-addresses",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "login": {
      "sections": {
        "main": {
          "type": "main-login",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "order": {
      "sections": {
        "main": {
          "type": "main-order",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "register": {
      "sections": {
        "main": {
          "type": "main-register",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    },
    "reset_password": {
      "sections": {
        "main": {
          "type": "main-reset-password",
          "settings": {}
        }
      },
      "order": [
        "main"
      ]
    }
  },
  "sectionGroups": {
    "footer-group": {
      "type": "footer",
      "name": "t:general.footer",
      "sections": {
        "footer": {
          "type": "footer",
          "settings": {
            "menu": "footer",
            "show_payment_icons": true
          }
        }
      },
      "order": [
        "footer"
      ]
    },
    "header-group": {
      "type": "header",
      "name": "t:general.header",
      "sections": {
        "announcement-bar": {
          "type": "announcement-bar",
          "blocks": {
            "message-1": {
              "type": "message",
              "settings": {
                "text": "Free shipping on orders over $50"
              }
            }
          },
          "block_order": [
            "message-1"
          ],
          "settings": {}
        },
        "header": {
          "type": "header",
          "settings": {}
        }
      },
      "order": [
        "announcement-bar",
        "header"
      ]
    },
    "overlay-group": {
      "type": "aside",
      "name": "t:general.overlays",
      "sections": {
        "cart-drawer": {
          "type": "cart-drawer",
          "settings": {
            "voucher_code": "WELCOME20",
            "voucher_text": "Get 20% off your first order"
          }
        }
      },
      "order": [
        "cart-drawer"
      ]
    }
  },
  "settingsSchema": [
    {
      "name": "theme_info",
      "theme_name": "Zalify",
      "theme_version": "3.2.0",
      "theme_author": "Zalify",
      "theme_documentation_url": "https://zalify.com",
      "theme_support_url": "https://zalify.com"
    },
    {
      "name": "t:general.brand",
      "settings": [
        {
          "type": "text",
          "id": "brand_name",
          "label": "t:labels.brand_name",
          "info": "t:info.brand_name"
        }
      ]
    },
    {
      "name": "t:general.favicon",
      "settings": [
        {
          "type": "image_picker",
          "id": "favicon",
          "label": "t:labels.favicon",
          "info": "t:info.favicon"
        }
      ]
    },
    {
      "name": "t:general.typography",
      "settings": [
        {
          "type": "header",
          "content": "t:general.fonts"
        },
        {
          "type": "font_picker",
          "id": "type_body_font",
          "default": "work_sans_n4",
          "label": "t:labels.body_font"
        },
        {
          "type": "text",
          "id": "type_body_google",
          "label": "t:labels.body_google_font",
          "info": "t:info.google_font"
        },
        {
          "type": "font_picker",
          "id": "type_heading_font",
          "default": "work_sans_n4",
          "label": "t:labels.heading_font"
        },
        {
          "type": "text",
          "id": "type_heading_google",
          "label": "t:labels.heading_google_font",
          "info": "t:info.google_font"
        },
        {
          "type": "text",
          "id": "type_mono_google",
          "label": "t:labels.mono_google_font",
          "info": "t:info.google_font_mono"
        }
      ]
    },
    {
      "name": "t:general.layout",
      "settings": [
        {
          "type": "select",
          "id": "max_page_width",
          "label": "t:labels.page_width",
          "options": [
            {
              "value": "90rem",
              "label": "t:options.page_width.narrow"
            },
            {
              "value": "110rem",
              "label": "t:options.page_width.wide"
            }
          ],
          "default": "90rem"
        },
        {
          "type": "range",
          "id": "min_page_margin",
          "min": 10,
          "max": 100,
          "step": 1,
          "unit": "px",
          "label": "t:labels.page_margin",
          "default": 20
        }
      ]
    },
    {
      "name": "t:general.colors",
      "settings": [
        {
          "type": "color_scheme_group",
          "id": "color_schemes",
          "definition": [
            {
              "type": "color",
              "id": "background",
              "label": "t:labels.background",
              "default": "#FFFFFF"
            },
            {
              "type": "color",
              "id": "text",
              "label": "t:labels.text",
              "default": "#1A1A1A"
            },
            {
              "type": "color",
              "id": "accent",
              "label": "t:labels.accent",
              "default": "#F26B8A"
            },
            {
              "type": "color",
              "id": "button",
              "label": "t:labels.button",
              "default": "#1A1A1A"
            },
            {
              "type": "color",
              "id": "button_label",
              "label": "t:labels.button_label",
              "default": "#FFFFFF"
            }
          ],
          "role": {
            "background": "background",
            "text": "text",
            "primary_button": "button",
            "on_primary_button": "button_label",
            "primary_button_border": "button",
            "secondary_button": "background",
            "on_secondary_button": "text",
            "secondary_button_border": "text",
            "icons": "text",
            "links": "text"
          }
        }
      ]
    },
    {
      "name": "t:general.social_media",
      "settings": [
        {
          "type": "text",
          "id": "social_instagram",
          "label": "t:labels.social_instagram"
        },
        {
          "type": "text",
          "id": "social_tiktok",
          "label": "t:labels.social_tiktok"
        },
        {
          "type": "text",
          "id": "social_x",
          "label": "t:labels.social_x"
        },
        {
          "type": "text",
          "id": "social_facebook",
          "label": "t:labels.social_facebook"
        },
        {
          "type": "text",
          "id": "social_youtube",
          "label": "t:labels.social_youtube"
        },
        {
          "type": "text",
          "id": "social_pinterest",
          "label": "t:labels.social_pinterest"
        }
      ]
    },
    {
      "name": "t:general.product_cards",
      "settings": [
        {
          "type": "select",
          "id": "card_swatch_style",
          "label": "t:labels.card_swatch_style",
          "options": [
            {
              "value": "swatch",
              "label": "t:options.swatch_style.swatches"
            },
            {
              "value": "variant_image",
              "label": "t:options.swatch_style.variant_images"
            },
            {
              "value": "none",
              "label": "t:options.swatch_style.none"
            }
          ],
          "default": "variant_image"
        },
        {
          "type": "select",
          "id": "card_density",
          "label": "t:labels.density",
          "options": [
            {
              "value": "comfortable",
              "label": "t:options.density.comfortable"
            },
            {
              "value": "compact",
              "label": "t:options.density.compact"
            }
          ],
          "default": "comfortable"
        },
        {
          "type": "checkbox",
          "id": "card_show_quick_add",
          "label": "t:labels.show_quick_add",
          "default": true
        },
        {
          "type": "checkbox",
          "id": "card_show_secondary_image",
          "label": "t:labels.show_secondary_image",
          "default": true
        },
        {
          "type": "checkbox",
          "id": "card_show_rating",
          "label": "t:labels.show_rating",
          "info": "t:info.show_rating",
          "default": false
        },
        {
          "type": "paragraph",
          "content": "t:info.swatch_colors"
        }
      ]
    },
    {
      "name": "t:general.badges",
      "settings": [
        {
          "type": "select",
          "id": "card_badge_position",
          "label": "t:labels.badge_position",
          "options": [
            {
              "value": "corner",
              "label": "t:options.badge_position.on_image"
            },
            {
              "value": "below",
              "label": "t:options.badge_position.below_image"
            }
          ],
          "default": "corner"
        },
        {
          "type": "color",
          "id": "card_badge_background",
          "label": "t:labels.badge_background",
          "default": "#F9EDEF"
        },
        {
          "type": "color",
          "id": "card_badge_text",
          "label": "t:labels.badge_text",
          "default": "#1A1A1A"
        },
        {
          "type": "color",
          "id": "card_badge_sale_background",
          "label": "t:labels.sale_badge_background",
          "default": "#F26B8A"
        },
        {
          "type": "color",
          "id": "card_badge_sale_text",
          "label": "t:labels.sale_badge_text",
          "default": "#FFFFFF"
        },
        {
          "type": "header",
          "content": "t:general.badge_style_1"
        },
        {
          "type": "text",
          "id": "badge_style_1_labels",
          "label": "t:labels.badge_labels",
          "info": "t:info.badge_labels",
          "default": "New"
        },
        {
          "type": "color",
          "id": "badge_style_1_background",
          "label": "t:labels.badge_background",
          "default": "#1A1A1A"
        },
        {
          "type": "color",
          "id": "badge_style_1_text",
          "label": "t:labels.badge_text",
          "default": "#FFFFFF"
        },
        {
          "type": "header",
          "content": "t:general.badge_style_2"
        },
        {
          "type": "text",
          "id": "badge_style_2_labels",
          "label": "t:labels.badge_labels",
          "info": "t:info.badge_labels"
        },
        {
          "type": "color",
          "id": "badge_style_2_background",
          "label": "t:labels.badge_background",
          "default": "#F9EDEF"
        },
        {
          "type": "color",
          "id": "badge_style_2_text",
          "label": "t:labels.badge_text",
          "default": "#1A1A1A"
        },
        {
          "type": "paragraph",
          "content": "t:info.badge_metaobjects"
        }
      ]
    },
    {
      "name": "t:general.appearance",
      "settings": [
        {
          "type": "header",
          "content": "t:general.corner_radius"
        },
        {
          "type": "range",
          "id": "button_corner_radius",
          "min": 0,
          "max": 30,
          "step": 1,
          "unit": "px",
          "label": "t:labels.button_corner_radius",
          "default": 0
        },
        {
          "type": "range",
          "id": "input_corner_radius",
          "min": 0,
          "max": 10,
          "step": 1,
          "unit": "px",
          "label": "t:labels.input_corner_radius",
          "default": 0
        },
        {
          "type": "range",
          "id": "card_corner_radius",
          "min": 0,
          "max": 30,
          "step": 1,
          "unit": "px",
          "label": "t:labels.card_corner_radius",
          "default": 0
        }
      ]
    }
  ],
  "settingsData": {
    "current": "Zalify",
    "presets": {
      "Zalify": {
        "type_body_font": "work_sans_n4",
        "type_heading_font": "work_sans_n4",
        "max_page_width": "90rem",
        "min_page_margin": 20,
        "button_corner_radius": 0,
        "input_corner_radius": 0,
        "card_corner_radius": 0,
        "card_swatch_style": "variant_image",
        "card_badge_background": "#F9EDEF",
        "card_badge_text": "#1A1A1A",
        "card_badge_sale_background": "#F26B8A",
        "card_badge_sale_text": "#FFFFFF",
        "color_schemes": {
          "scheme-1": {
            "settings": {
              "background": "#FFFFFF",
              "text": "#1A1A1A",
              "accent": "#F26B8A",
              "button": "#1A1A1A",
              "button_label": "#FFFFFF"
            }
          },
          "scheme-2": {
            "settings": {
              "background": "#F9EDEF",
              "text": "#1A1A1A",
              "accent": "#F26B8A",
              "button": "#1A1A1A",
              "button_label": "#FFFFFF"
            }
          },
          "scheme-3": {
            "settings": {
              "background": "#F6F4F0",
              "text": "#1A1A1A",
              "accent": "#F26B8A",
              "button": "#1A1A1A",
              "button_label": "#FFFFFF"
            }
          },
          "scheme-4": {
            "settings": {
              "background": "#1A1A1A",
              "text": "#FFFFFF",
              "accent": "#F26B8A",
              "button": "#FFFFFF",
              "button_label": "#1A1A1A"
            }
          }
        }
      }
    }
  },
  "locales": {
    "en.default": {
      "404": {
        "title": "404",
        "not_found": "Page not found.",
        "back_to_shopping": "Back to shopping"
      },
      "blog": {
        "article_comments": "Comments",
        "article_metadata_html": "{{ date }} by {{ author }}",
        "back_to_blog": "Back to {{ blog }}",
        "comment_form_body": "Comment",
        "comment_form_email": "Email",
        "comment_form_name": "Name",
        "comment_form_submit": "Post",
        "comment_form_title": "Add a comment",
        "comment_success": "Your comment was posted successfully.",
        "comment_success_moderated": "Your comment was posted successfully. It will be visible once approved.",
        "empty": "No posts yet — check back soon."
      },
      "cart": {
        "add": "Add",
        "bag": "Bag",
        "checkout": "Checkout",
        "continue_shopping": "Continue shopping",
        "decrease": "Decrease quantity",
        "disclaimer_shipping": "Shipping and promotions calculated in checkout.",
        "disclaimer_tax": "Sales tax shown in checkout is a best estimate and may differ from the amount actually charged.",
        "empty": "Your cart is empty.",
        "estimated_total": "Estimated total",
        "free_shipping_over": "Free standard shipping over {{ amount }}",
        "free_shipping_progress_html": "You're {{ remaining }} away from free standard shipping",
        "free_shipping_unlocked": "Congrats! You get free standard shipping",
        "increase": "Increase quantity",
        "note": "Shipping and taxes calculated at checkout.",
        "note_label": "Order note",
        "note_placeholder": "How can we help?",
        "quantity": "Quantity",
        "recommendations": "You may also like",
        "remove": "Remove",
        "savings": "Savings",
        "shipping": "Shipping",
        "subtotal": "Subtotal",
        "tax_note": "Tax calculated in checkout",
        "taxes_included": "Tax included",
        "terms_html": "By checking out, you agree to our {{ terms_link }} and {{ privacy_link }}.",
        "title": "Cart",
        "update": "Update",
        "voucher_apply": "Apply",
        "voucher_applied": "Applied",
        "voucher_error": "This code can't be applied to your cart right now."
      },
      "collections": {
        "empty": "No products found.",
        "title": "Collections",
        "view_all": "View all"
      },
      "contact": {
        "name": "Name",
        "email": "Email",
        "phone": "Phone number (optional)",
        "message": "Message",
        "send": "Send message",
        "success": "Thanks for reaching out. We’ll get back to you as soon as we can."
      },
      "customers": {
        "account": {
          "title": "Account",
          "orders": "Order history",
          "no_orders": "You have not placed any orders yet.",
          "view_addresses": "Addresses ({{ count }})",
          "log_out": "Log out"
        },
        "activate_account": {
          "title": "Activate account",
          "subtext": "Create your password to activate your account.",
          "submit": "Activate account",
          "decline": "Decline invitation"
        },
        "addresses": {
          "title": "Addresses",
          "default": "Default address",
          "add_new": "Add a new address",
          "edit": "Edit",
          "delete": "Delete",
          "confirm_delete": "Are you sure you want to delete this address?",
          "first_name": "First name",
          "last_name": "Last name",
          "company": "Company",
          "address1": "Address line 1",
          "address2": "Address line 2",
          "city": "City",
          "country": "Country/region",
          "province": "Province",
          "zip": "Postal/ZIP code",
          "phone": "Phone",
          "set_default": "Set as default address",
          "save": "Save address"
        },
        "login": {
          "title": "Login",
          "email": "Email",
          "password": "Password",
          "submit": "Sign in",
          "create_account": "Create account"
        },
        "order": {
          "title": "Order {{ name }}",
          "date_html": "Placed on {{ date }}",
          "cancelled_html": "Order cancelled on {{ date }}",
          "cancelled_reason": "Reason: {{ reason }}",
          "return_to_account": "Return to account",
          "product": "Product",
          "price": "Price",
          "quantity": "Quantity",
          "total": "Total",
          "subtotal": "Subtotal",
          "shipping": "Shipping",
          "tax": "Tax",
          "fulfilled_at": "Fulfilled",
          "track_shipment": "Track shipment",
          "billing_address": "Billing address",
          "shipping_address": "Shipping address"
        },
        "orders": {
          "order_number": "Order",
          "date": "Date",
          "payment_status": "Payment status",
          "fulfillment_status": "Fulfillment status",
          "total": "Total"
        },
        "recover": {
          "title": "Forgot your password?",
          "subtext": "Enter your email and we will send you a link to reset your password.",
          "submit": "Send reset link",
          "success": "If that email address is in our system, you will receive an email with instructions to reset your password shortly."
        },
        "register": {
          "title": "Create account",
          "first_name": "First name",
          "last_name": "Last name",
          "submit": "Create account",
          "sign_in": "Already have an account? Sign in"
        },
        "reset_password": {
          "title": "Reset account password",
          "subtext": "Enter a new password for {{ email }}",
          "password": "Password",
          "password_confirm": "Confirm password",
          "submit": "Reset password"
        }
      },
      "facets": {
        "apply": "Apply",
        "cancel": "Cancel",
        "clear_all": "Clear all",
        "filter": "Filter",
        "filters": "Filters",
        "from": "From",
        "items": {
          "one": "{{ count }} item",
          "other": "{{ count }} items"
        },
        "sort": "Sort",
        "sort_by": "Sort by",
        "to": "To"
      },
      "general": {
        "account": "Account",
        "article": "Article",
        "close": "Close",
        "countdown": {
          "days": "days",
          "hours": "hours",
          "minutes": "min",
          "seconds": "sec"
        },
        "country": "Country/region",
        "footer_navigation": "Footer navigation",
        "go_to_slide": "Go to slide {{ number }}",
        "language": "Language",
        "log_in": "Log in",
        "menu": "Menu",
        "next": "Next",
        "page": "Page",
        "pause": "Pause",
        "previous": "Previous",
        "update": "Update",
        "play_video": "Play video"
      },
      "gift_card": {
        "add_to_apple_wallet": "Add to Apple Wallet",
        "card": "Gift card",
        "expired": "This gift card has expired",
        "expires_on": "Expires on {{ expires_on }}",
        "qr_code": "QR code — scan to redeem gift card",
        "use_at_checkout": "Use this gift card at checkout"
      },
      "newsletter": {
        "email": "Email",
        "heading": "Stay in the loop",
        "submit": "Subscribe",
        "success": "Thanks for subscribing."
      },
      "password": {
        "title": "This shop is private",
        "password": "Password",
        "enter": "Enter"
      },
      "products": {
        "add_to_bag": "Add to bag",
        "add_to_cart": "Add to cart",
        "best_seller": "Best seller",
        "choose_options": "Choose options",
        "complementary": "Pairs well with",
        "next_image": "Next image",
        "one_time_purchase": "One-time purchase",
        "pickup": {
          "available_at": "Pickup available at {{ location }}",
          "unavailable_at": "Pickup currently unavailable at {{ location }}"
        },
        "previous_image": "Previous image",
        "purchase_options": "Purchase options",
        "quantity": "Quantity",
        "rating_label": "Rated {{ rating }} out of {{ max }} stars ({{ count }} reviews)",
        "recipient": {
          "checkbox": "I want to send this as a gift",
          "email": "Recipient email",
          "name": "Recipient name (optional)",
          "message": "Message (optional)",
          "send_on": "Send on (optional)"
        },
        "recommendations": "You may also like",
        "sale": "Sale",
        "sold_out": "Sold out",
        "unavailable": "Unavailable",
        "unit_price_label": "Unit price",
        "zoom_image": "Zoom image",
        "size_guide": "Size guide",
        "size_option_match": "size",
        "view_product": "View product",
        "color_option_match": "color,colour"
      },
      "search": {
        "title": "Search",
        "placeholder": "Looking for something?",
        "submit": "Search",
        "no_results_html": "No results found for {{ terms }}",
        "results_for_html": "{{ count }} results found for {{ terms }}",
        "view_all": "View all results"
      }
    },
    "en.default.schema": {
      "general": {
        "404": "Not found",
        "accordion": "Accordion",
        "account": "Account",
        "activate_account": "Activate account",
        "addresses": "Addresses",
        "announcement_bar": "Announcement bar",
        "appearance": "Appearance",
        "article": "Article",
        "badge_style_1": "Badge style 1",
        "badge_style_2": "Badge style 2",
        "badges": "Badges",
        "block": "Block",
        "blog": "Blog",
        "brand": "Brand",
        "button": "Button",
        "buy_buttons": "Buy buttons",
        "cart": "Cart",
        "cart_drawer": "Cart drawer",
        "collection": "Collection",
        "collection_card": "Collection card",
        "collections": "Collections",
        "collections_grid": "Collections grid",
        "colors": "Colors",
        "column": "Column",
        "complementary_products": "Complementary products",
        "contact_form": "Contact form",
        "content": "Content",
        "content_box": "Content box",
        "corner_radius": "Corner radius",
        "countdown": "Countdown",
        "custom_liquid": "Custom Liquid",
        "custom_section": "Custom section",
        "description": "Description",
        "favicon": "Favicon",
        "featured_collection": "Featured collection",
        "fonts": "Fonts",
        "footer": "Footer",
        "group": "Group",
        "header": "Header",
        "hero": "Hero",
        "image": "Image",
        "image_with_text": "Image with text",
        "layout": "Layout",
        "login": "Login",
        "main": "Main",
        "mega_promo": "Mega menu promo",
        "multicolumn": "Multicolumn",
        "order": "Order",
        "overlays": "Overlays",
        "page": "Page",
        "password": "Password",
        "primary": "Primary",
        "product": "Product",
        "product_cards": "Product cards",
        "product_recommendations": "Product recommendations",
        "promo_1": "Promo 1",
        "promo_2": "Promo 2",
        "promo_3": "Promo 3",
        "promo_4": "Promo 4",
        "promo_5": "Promo 5",
        "promo_6": "Promo 6",
        "promo_card": "Promo card",
        "quantity_selector": "Quantity selector",
        "quick_add": "Quick add",
        "quote": "Quote",
        "register": "Register",
        "reset_password": "Reset password",
        "rich_text": "Rich text",
        "row": "Row",
        "search": "Search",
        "secondary": "Secondary",
        "section": "Section",
        "settings": "Settings",
        "sidebar": "Sidebar",
        "size_guide": "Size guide",
        "social_media": "Social media",
        "spacer": "Spacer",
        "stories": "Stories",
        "story": "Story",
        "testimonials": "Testimonials",
        "text": "Text",
        "theme": "Theme",
        "title_price": "Title & price",
        "typography": "Typography",
        "variant_picker": "Variant picker",
        "video": "Video",
        "video_bubble": "Video bubble",
        "video_card": "Video card",
        "video_carousel": "Video carousel",
        "voucher": "Voucher"
      },
      "labels": {
        "accent": "Accent",
        "alignment": "Alignment",
        "aspect_ratio": "Aspect ratio",
        "author": "Author",
        "autoplay": "Autoplay",
        "backdrop": "Text backdrop",
        "background": "Background",
        "badge_background": "Badge background",
        "badge_labels": "Labels",
        "badge_position": "Badge position",
        "badge_text": "Badge text",
        "body_font": "Body font",
        "body_google_font": "Body Google font",
        "brand_name": "Brand name",
        "button": "Button",
        "button_corner_radius": "Button corner radius",
        "button_label": "Button label",
        "button_style": "Button style",
        "caption": "Caption",
        "card_corner_radius": "Card and image corner radius",
        "card_swatch_style": "Variant display",
        "card_transparent": "Transparent text background",
        "collection": "Collection",
        "color_scheme": "Color scheme",
        "columns": "Columns",
        "completed_text": "Completed text",
        "content": "Content",
        "content_position": "Content position",
        "cover_image": "Cover image",
        "custom_liquid": "Liquid code",
        "customer_account_menu": "Customer account menu",
        "density": "Density",
        "desktop_image": "Desktop image",
        "desktop_item_size": "Desktop item size",
        "desktop_media_layout": "Desktop media layout",
        "enable_follow_on_shop": "Enable Follow on Shop",
        "end_time": "End time",
        "eyebrow": "Eyebrow",
        "favicon": "Favicon image",
        "fill_space": "Fill available space",
        "foreground": "Foreground",
        "free_shipping_threshold": "Free shipping threshold",
        "grid_gap": "Grid spacing",
        "grid_item_width": "Grid item width",
        "heading": "Heading",
        "heading_font": "Heading font",
        "heading_google_font": "Heading Google font",
        "height": "Height",
        "horizontal_position": "Horizontal position",
        "image": "Image",
        "image_position": "Image position",
        "input_corner_radius": "Input corner radius",
        "label": "Label",
        "layout": "Layout",
        "layout_direction": "Layout direction",
        "link": "Link",
        "logo": "Logo",
        "logo_width": "Logo width",
        "main_video": "Main video",
        "menu": "Menu",
        "menu_item": "Menu item title",
        "message": "Message",
        "mobile_image": "Mobile image",
        "mobile_item_size": "Mobile item size",
        "mobile_media_layout": "Mobile media layout",
        "mobile_video": "Mobile video",
        "mono_google_font": "Monospace Google font",
        "padding": "Padding",
        "page_margin": "Page margin",
        "page_width": "Page width",
        "position": "Position",
        "preview_video": "Preview video",
        "product": "Product",
        "products_to_show": "Products to show",
        "quote": "Quote",
        "recommendation_type": "Recommendation type",
        "recommendations_collection": "Recommendations collection",
        "rotation_speed": "Rotation speed",
        "rows": "Rows",
        "sale_badge_background": "Sale badge background",
        "sale_badge_text": "Sale badge text",
        "secondary_menu": "Secondary menu",
        "section_spacing": "Section spacing",
        "shape": "Shape",
        "show_badges": "Show badges",
        "show_card": "Show content card",
        "show_country_selector": "Show country/region selector",
        "show_dynamic_checkout": "Show dynamic checkout button",
        "show_featured_post": "Show featured post",
        "show_locale_selector": "Show language selector",
        "show_newsletter": "Show newsletter signup",
        "show_payment_icons": "Show payment icons",
        "show_quick_add": "Show quick add button",
        "show_rating": "Show product rating",
        "show_secondary_image": "Show second image on hover",
        "show_sticky_bar": "Show sticky add-to-cart bar on mobile",
        "show_thumbnails": "Show thumbnails",
        "size": "Size",
        "size_guide_page": "Size guide page",
        "slide": "Slide",
        "social_facebook": "Facebook",
        "social_instagram": "Instagram",
        "social_pinterest": "Pinterest",
        "social_tiktok": "TikTok",
        "social_x": "X (Twitter)",
        "social_youtube": "YouTube",
        "text": "Text",
        "text_style": "Text style",
        "transparent_header": "Transparent on home page",
        "transparent_text_color": "Transparent text color",
        "vertical_position": "Vertical position",
        "video": "Video",
        "video_url": "Video URL",
        "voucher_code": "Discount code",
        "voucher_text": "Description"
      },
      "info": {
        "backdrop": "Paints the content box with the scheme background.",
        "badge_labels": "Comma-separated. A product tagged \"badge:New\" matches a list containing \"New\" and uses this style; unmatched labels use the standard badge colors.",
        "badge_metaobjects": "Need more styles? Create a metaobject definition with type \"badge_style\" and fields \"labels\" (single line text), \"background\" (color), and \"text\" (color) — every entry becomes an extra badge style, matched the same way.",
        "brand_name": "Shown as the header wordmark and in the footer instead of the Shopify store name.",
        "countdown_completed": "Shown when the deadline passes. Leave empty to hide the countdown instead.",
        "countdown_end": "Include a timezone so every visitor sees the same deadline, e.g. 2026-08-01T00:00:00+08:00 (also accepts 2026/08/01 00:00:00+0800).",
        "custom_liquid": "Add app snippets or other Liquid code to create advanced customizations.",
        "favicon": "Will be scaled down to 32 x 32px",
        "fill_space": "Grows to push surrounding blocks apart in stretched layouts. The height acts as a minimum.",
        "free_shipping_threshold": "In your store's currency. Set to 0 to hide the free shipping bar.",
        "google_font": "Exact Google Fonts family name, e.g. \"Space Grotesk\". Overrides the font picker above and loads from Google's CDN.",
        "google_font_mono": "Exact Google Fonts family name, e.g. \"Space Mono\". Loads from Google's CDN; falls back to the system monospace font.",
        "hero_link": "Makes the whole slide clickable. Buttons in the content stay on top.",
        "hero_mobile_video": "Optional. Plays instead of the desktop video on small screens.",
        "hero_video": "Autoplays muted on a loop and replaces the images.",
        "main_video": "Plays with sound in the expanded player. Falls back to the preview video.",
        "menu_item": "Must exactly match the title of a top-level menu item.",
        "mobile_image": "Optional. Shown instead of the desktop image on small screens.",
        "preview_video": "A short, silent clip that loops in place. Keep it a few seconds long.",
        "promo_position": "Which card slot the promo occupies, counting from the first product. Applies to the first page only.",
        "show_rating": "Reads the standard review metafields written by review apps (Judge.me, Loox, Yotpo, ...). Hidden for products without reviews.",
        "size_guide": "Shown as a link next to size options; the page opens in a dialog.",
        "swatch_colors": "Swatches use the colors set on product option values in your admin. For names without one, create a metaobject definition with type \"swatch_color\" and fields \"labels\" (single line text), \"color\" (color), and \"image\" (file) — entries match option and filter values by name.",
        "transparent_header": "Overlays the first section until scrolled; best with a full-height hero. Image logos keep their colors — use a text logo or a light logo image.",
        "video_autoplay": "Plays muted on a loop. Turn off for a cover image with a play button, controls, and sound.",
        "video_product": "Shown with the expanded video, linking to the product.",
        "video_url": "YouTube or Vimeo link, used when no video file is selected above. Loads only after the cover is clicked.",
        "voucher_code": "Shown in the cart with a one-tap Apply action. Create the code in your Shopify admin under Discounts first."
      },
      "options": {
        "media_layout": {
          "carousel": "Carousel",
          "stacked": "Stacked",
          "full": "Full width",
          "peek": "Peek next image"
        },
        "badge_position": {
          "on_image": "On image",
          "below_image": "Below image"
        },
        "aspect": {
          "auto": "Auto",
          "square": "Square",
          "portrait": "Portrait",
          "landscape": "Landscape"
        },
        "alignment": {
          "left": "Left",
          "center": "Center",
          "right": "Right"
        },
        "direction": {
          "horizontal": "Horizontal",
          "vertical": "Vertical"
        },
        "layout": {
          "grid": "Grid",
          "row": "Horizontal scroll"
        },
        "page_width": {
          "narrow": "Narrow",
          "wide": "Wide"
        },
        "section_spacing": {
          "none": "None",
          "small": "Small",
          "medium": "Medium",
          "large": "Large"
        },
        "shape": {
          "circle": "Circle",
          "square": "Square"
        },
        "size": {
          "large": "Large",
          "medium": "Medium",
          "small": "Small"
        },
        "swatch_style": {
          "swatches": "Color swatches",
          "variant_images": "Variant images",
          "none": "None"
        },
        "text_style": {
          "title": "Title",
          "subtitle": "Subtitle",
          "normal": "Normal text",
          "display": "Display",
          "eyebrow": "Eyebrow"
        },
        "vertical": {
          "top": "Top",
          "middle": "Middle",
          "bottom": "Bottom"
        },
        "recommendations": {
          "related": "Related products",
          "complementary": "Complementary products"
        },
        "density": {
          "comfortable": "Comfortable",
          "compact": "Compact"
        }
      }
    }
  }
} as unknown as ThemeSchema;
